
import React from "react";


class Dropdown extends React.Component {
    // constructor(props) {
    // super(props);
    // console.log("props");
    // }

    render() {
        return (
            <div>
                <div data-phone-code="93">Afghanistan +93</div>
                <div data-phone-code="358">Aland Islands +358</div>
                <div data-phone-code="355">Albania +355</div>
                <div data-phone-code="213">Algeria +213</div>
                <div data-phone-code="1684">American Samoa +1684</div>
                <div data-phone-code="376">Andorra +376</div>
                <div data-phone-code="244">Angola +244</div>
                <div data-phone-code="1264">Anguilla +1264</div>
                <div data-phone-code="672">Antarctica +672</div>
                <div data-phone-code="1268">Antigua and Barbuda +1268</div>
                <div data-phone-code="54">Argentina +54</div>
                <div data-phone-code="374">Armenia +374</div>
                <div data-phone-code="297">Aruba +297</div>
                <div data-phone-code="61">Australia +61</div>
                <div data-phone-code="43">Austria +43</div>
                <div data-phone-code="994">Azerbaijan +994</div>
                <div data-phone-code="1242">Bahamas +1242</div>
                <div data-phone-code="973">Bahrain +973</div>
                <div data-phone-code="880">Bangladesh +880</div>
                <div data-phone-code="1246">Barbados +1246</div>
                <div data-phone-code="375">Belarus +375</div>
                <div data-phone-code="32">Belgium +32</div>
                <div data-phone-code="501">Belize +501</div>
                <div data-phone-code="229">Benin +229</div>
                <div data-phone-code="1441">Bermuda +1441</div>
                <div data-phone-code="975">Bhutan +975</div>
                <div data-phone-code="591">Bolivia +591</div>
                <div data-phone-code="599">Bonaire, Sint Eustatius and Saba +599</div>
                <div data-phone-code="387">Bosnia and Herzegovina +387</div>
                <div data-phone-code="267">Botswana +267</div>
                <div data-phone-code="55">Bouvet Island +55</div>
                <div data-phone-code="55">Brazil +55</div>
                <div data-phone-code="246">British Indian Ocean Territory +246</div>
                <div data-phone-code="673">Brunei Darussalam +673</div>
                <div data-phone-code="359">Bulgaria +359</div>
                <div data-phone-code="226">Burkina Faso +226</div>
                <div data-phone-code="257">Burundi +257</div>
                <div data-phone-code="855">Cambodia +855</div>
                <div data-phone-code="237">Cameroon +237</div>
                <div data-phone-code="1">Canada +1</div>
                <div data-phone-code="238">Cape Verde +238</div>
                <div data-phone-code="1345">Cayman Islands +1345</div>
                <div data-phone-code="236">Central African Republic +236</div>
                <div data-phone-code="235">Chad +235</div>
                <div data-phone-code="56">Chile +56</div>
                <div data-phone-code="86">China +86</div>
                <div data-phone-code="61">Christmas Island +61</div>
                <div data-phone-code="672">Cocos (Keeling) Islands +672</div>
                <div data-phone-code="57">Colombia +57</div>
                <div data-phone-code="269">Comoros +269</div>
                <div data-phone-code="242">Congo +242</div>
                <div data-phone-code="242">Congo, Democratic Republic of the Congo +242</div>
                <div data-phone-code="682">Cook Islands +682</div>
                <div data-phone-code="506">Costa Rica +506</div>
                <div data-phone-code="225">Cote D'Ivoire +225</div>
                <div data-phone-code="385">Croatia +385</div>
                <div data-phone-code="53">Cuba +53</div>
                <div data-phone-code="599">Curacao +599</div>
                <div data-phone-code="357">Cyprus +357</div>
                <div data-phone-code="420">Czech Republic +420</div>
                <div data-phone-code="45">Denmark +45</div>
                <div data-phone-code="253">Djibouti +253</div>
                <div data-phone-code="1767">Dominica +1767</div>
                <div data-phone-code="1809">Dominican Republic +1809</div>
                <div data-phone-code="593">Ecuador +593</div>
                <div data-phone-code="20">Egypt +20</div>
                <div data-phone-code="503">El Salvador +503</div>
                <div data-phone-code="240">Equatorial Guinea +240</div>
                <div data-phone-code="291">Eritrea +291</div>
                <div data-phone-code="372">Estonia +372</div>
                <div data-phone-code="251">Ethiopia +251</div>
                <div data-phone-code="500">Falkland Islands (Malvinas) +500</div>
                <div data-phone-code="298">Faroe Islands +298</div>
                <div data-phone-code="679">Fiji +679</div>
                <div data-phone-code="358">Finland +358</div>
                <div data-phone-code="33">France +33</div>
                <div data-phone-code="594">French Guiana +594</div>
                <div data-phone-code="689">French Polynesia +689</div>
                <div data-phone-code="262">French Southern Territories +262</div>
                <div data-phone-code="241">Gabon +241</div>
                <div data-phone-code="220">Gambia +220</div>
                <div data-phone-code="995">Georgia +995</div>
                <div data-phone-code="49">Germany +49</div>
                <div data-phone-code="233">Ghana +233</div>
                <div data-phone-code="350">Gibraltar +350</div>
                <div data-phone-code="30">Greece +30</div>
                <div data-phone-code="299">Greenland +299</div>
                <div data-phone-code="1473">Grenada +1473</div>
                <div data-phone-code="590">Guadeloupe +590</div>
                <div data-phone-code="1671">Guam +1671</div>
                <div data-phone-code="502">Guatemala +502</div>
                <div data-phone-code="44">Guernsey +44</div>
                <div data-phone-code="224">Guinea +224</div>
                <div data-phone-code="245">Guinea-Bissau +245</div>
                <div data-phone-code="592">Guyana +592</div>
                <div data-phone-code="509">Haiti +509</div>
                <div data-phone-code="0">Heard Island and Mcdonald Islands +0</div>
                <div data-phone-code="39">Holy See (Vatican City State) +39</div>
                <div data-phone-code="504">Honduras +504</div>
                <div data-phone-code="852">Hong Kong +852</div>
                <div data-phone-code="36">Hungary +36</div>
                <div data-phone-code="354">Iceland +354</div>
                <div data-phone-code="91">India +91</div>
                <div data-phone-code="62">Indonesia +62</div>
                <div data-phone-code="98">Iran, Islamic Republic of +98</div>
                <div data-phone-code="964">Iraq +964</div>
                <div data-phone-code="353">Ireland +353</div>
                <div data-phone-code="44">Isle of Man +44</div>
                <div data-phone-code="972">Israel +972</div>
                <div data-phone-code="39">Italy +39</div>
                <div data-phone-code="1876">Jamaica +1876</div>
                <div data-phone-code="81">Japan +81</div>
                <div data-phone-code="44">Jersey +44</div>
                <div data-phone-code="962">Jordan +962</div>
                <div data-phone-code="7">Kazakhstan +7</div>
                <div data-phone-code="254">Kenya +254</div>
                <div data-phone-code="686">Kiribati +686</div>
                <div data-phone-code="850">Korea, Democratic People's Republic of +850</div>
                <div data-phone-code="82">Korea, Republic of +82</div>
                <div data-phone-code="381">Kosovo +381</div>
                <div data-phone-code="965">Kuwait +965</div>
                <div data-phone-code="996">Kyrgyzstan +996</div>
                <div data-phone-code="856">Lao People's Democratic Republic +856</div>
                <div data-phone-code="371">Latvia +371</div>
                <div data-phone-code="961">Lebanon +961</div>
                <div data-phone-code="266">Lesotho +266</div>
                <div data-phone-code="231">Liberia +231</div>
                <div data-phone-code="218">Libyan Arab Jamahiriya +218</div>
                <div data-phone-code="423">Liechtenstein +423</div>
                <div data-phone-code="370">Lithuania +370</div>
                <div data-phone-code="352">Luxembourg +352</div>
                <div data-phone-code="853">Macao +853</div>
                <div data-phone-code="389">Macedonia, the Former Yugoslav Republic of +389</div>
                <div data-phone-code="261">Madagascar +261</div>
                <div data-phone-code="265">Malawi +265</div>
                <div data-phone-code="60">Malaysia +60</div>
                <div data-phone-code="960">Maldives +960</div>
                <div data-phone-code="223">Mali +223</div>
                <div data-phone-code="356">Malta +356</div>
                <div data-phone-code="692">Marshall Islands +692</div>
                <div data-phone-code="596">Martinique +596</div>
                <div data-phone-code="222">Mauritania +222</div>
                <div data-phone-code="230">Mauritius +230</div>
                <div data-phone-code="269">Mayotte +269</div>
                <div data-phone-code="52">Mexico +52</div>
                <div data-phone-code="691">Micronesia, Federated States of +691</div>
                <div data-phone-code="373">Moldova, Republic of +373</div>
                <div data-phone-code="377">Monaco +377</div>
                <div data-phone-code="976">Mongolia +976</div>
                <div data-phone-code="382">Montenegro +382</div>
                <div data-phone-code="1664">Montserrat +1664</div>
                <div data-phone-code="212">Morocco +212</div>
                <div data-phone-code="258">Mozambique +258</div>
                <div data-phone-code="95">Myanmar +95</div>
                <div data-phone-code="264">Namibia +264</div>
                <div data-phone-code="674">Nauru +674</div>
                <div data-phone-code="977">Nepal +977</div>
                <div data-phone-code="31">Netherlands +31</div>
                <div data-phone-code="599">Netherlands Antilles +599</div>
                <div data-phone-code="687">New Caledonia +687</div>
                <div data-phone-code="64">New Zealand +64</div>
                <div data-phone-code="505">Nicaragua +505</div>
                <div data-phone-code="227">Niger +227</div>
                <div data-phone-code="234">Nigeria +234</div>
                <div data-phone-code="683">Niue +683</div>
                <div data-phone-code="672">Norfolk Island +672</div>
                <div data-phone-code="1670">Northern Mariana Islands +1670</div>
                <div data-phone-code="47">Norway +47</div>
                <div data-phone-code="968">Oman +968</div>
                <div data-phone-code="92">Pakistan +92</div>
                <div data-phone-code="680">Palau +680</div>
                <div data-phone-code="970">Palestinian Territory, Occupied +970</div>
                <div data-phone-code="507">Panama +507</div>
                <div data-phone-code="675">Papua New Guinea +675</div>
                <div data-phone-code="595">Paraguay +595</div>
                <div data-phone-code="51">Peru +51</div>
                <div data-phone-code="63">Philippines +63</div>
                <div data-phone-code="64">Pitcairn +64</div>
                <div data-phone-code="48">Poland +48</div>
                <div data-phone-code="351">Portugal +351</div>
                <div data-phone-code="1787">Puerto Rico +1787</div>
                <div data-phone-code="974">Qatar +974</div>
                <div data-phone-code="262">Reunion +262</div>
                <div data-phone-code="40">Romania +40</div>
                <div data-phone-code="70">Russian Federation +70</div>
                <div data-phone-code="250">Rwanda +250</div>
                <div data-phone-code="590">Saint Barthelemy +590</div>
                <div data-phone-code="290">Saint Helena +290</div>
                <div data-phone-code="1869">Saint Kitts and Nevis +1869</div>
                <div data-phone-code="1758">Saint Lucia +1758</div>
                <div data-phone-code="590">Saint Martin +590</div>
                <div data-phone-code="508">Saint Pierre and Miquelon +508</div>
                <div data-phone-code="1784">Saint Vincent and the Grenadines +1784</div>
                <div data-phone-code="684">Samoa +684</div>
                <div data-phone-code="378">San Marino +378</div>
                <div data-phone-code="239">Sao Tome and Principe +239</div>
                <div data-phone-code="966">Saudi Arabia +966</div>
                <div data-phone-code="221">Senegal +221</div>
                <div data-phone-code="381">Serbia +381</div>
                <div data-phone-code="381">Serbia and Montenegro +381</div>
                <div data-phone-code="248">Seychelles +248</div>
                <div data-phone-code="232">Sierra Leone +232</div>
                <div data-phone-code="65">Singapore +65</div>
                <div data-phone-code="1">Sint Maarten +1</div>
                <div data-phone-code="421">Slovakia +421</div>
                <div data-phone-code="386">Slovenia +386</div>
                <div data-phone-code="677">Solomon Islands +677</div>
                <div data-phone-code="252">Somalia +252</div>
                <div data-phone-code="27">South Africa +27</div>
                <div data-phone-code="500">South Georgia and the South Sandwich Islands +500</div>
                <div data-phone-code="211">South Sudan +211</div>
                <div data-phone-code="34">Spain +34</div>
                <div data-phone-code="94">Sri Lanka +94</div>
                <div data-phone-code="249">Sudan +249</div>
                <div data-phone-code="597">Suriname +597</div>
                <div data-phone-code="47">Svalbard and Jan Mayen +47</div>
                <div data-phone-code="268">Swaziland +268</div>
                <div data-phone-code="46">Sweden +46</div>
                <div data-phone-code="41">Switzerland +41</div>
                <div data-phone-code="963">Syrian Arab Republic +963</div>
                <div data-phone-code="886">Taiwan, Province of China +886</div>
                <div data-phone-code="992">Tajikistan +992</div>
                <div data-phone-code="255">Tanzania, United Republic of +255</div>
                <div data-phone-code="66">Thailand +66</div>
                <div data-phone-code="670">Timor-Leste +670</div>
                <div data-phone-code="228">Togo +228</div>
                <div data-phone-code="690">Tokelau +690</div>
                <div data-phone-code="676">Tonga +676</div>
                <div data-phone-code="1868">Trinidad and Tobago +1868</div>
                <div data-phone-code="216">Tunisia +216</div>
                <div data-phone-code="90">Turkey +90</div>
                <div data-phone-code="7370">Turkmenistan +7370</div>
                <div data-phone-code="1649">Turks and Caicos Islands +1649</div>
                <div data-phone-code="688">Tuvalu +688</div>
                <div data-phone-code="256">Uganda +256</div>
                <div data-phone-code="380">Ukraine +380</div>
                <div data-phone-code="971">United Arab Emirates +971</div>
                <div data-phone-code="44">United Kingdom +44</div>
                <div data-phone-code="1">United States +1</div>
                <div data-phone-code="1">United States Minor Outlying Islands +1</div>
                <div data-phone-code="598">Uruguay +598</div>
                <div data-phone-code="998">Uzbekistan +998</div>
                <div data-phone-code="678">Vanuatu +678</div>
                <div data-phone-code="58">Venezuela +58</div>
                <div data-phone-code="84">Viet Nam +84</div>
                <div data-phone-code="1284">Virgin Islands, British +1284</div>
                <div data-phone-code="1340">Virgin Islands, U.s. +1340</div>
                <div data-phone-code="681">Wallis and Futuna +681</div>
                <div data-phone-code="212">Western Sahara +212</div>
                <div data-phone-code="967">Yemen +967</div>
                <div data-phone-code="260">Zambia +260</div>
                <div data-phone-code="263">Zimbabwe +263</div>
            </div>
        )
    }
}

export default Login;